### ISSUE TITLE
no config specified

### ISSUE THREAD

**Issue by ckocyigit** [is-cool-me/dnscontrol-action#23]
I get "no config specified" errors when running the action with the provided templates.

```yaml
jobs:
  push:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: DNSControl push
        uses: is-cool-me/dnscontrol-action@v4.13.0
        env:
          NETCUP_API_KEY: ${{ secrets.NETCUP_API_KEY }}
          NETCUP_API_PASSWORD: ${{ secrets.NETCUP_API_PASSWORD }}
          NETCUP_CUSTOMER_NUMBER: ${{ secrets.NETCUP_CUSTOMER_NUMBER }}
        with:
          args: push
          config_file: 'dns/dnsconfig.js'
          creds_file: 'dns/creds.json'
```
workspace:

```
.
├── README.md
└── dns
    ├── creds.json
    └── dnsconfig.js
```
